theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true

params:
  plausible: levelesyeux.com
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"
  breadcrumb:
    position: after-hero
  summary:
    position: hero

redirects:
- force: true
  from: /collectif/qui-sommes-nous/
  status: 301
  to: /lassociation/