theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true

params:
  plausible: levelesyeux.com
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true

redirects:
- from: /collectif/qui-sommes-nous/
  to: /lassociation/
  status: 301
  force: false
- from: /collectif/qui-sommes-nous
  to: /lassociation/
  status: 301
  force: false
- from: collectif/qui-sommes-nous
  to: /lassociation/
  status: 301
  force: false
